### ISSUE TITLE
My first CosmWasm smart contract

### ISSUE THREAD

**Issue by jasny** [ltonetwork/smart-contract-experiments#2]
Create the `Adder` smart contract.

* It should have a public property `name` which is set through the constructor.
* It should have a stateful public property `value`.
* The value is updated through the `add(uint number)`.

**Comment by MbBrainz** [comment]
Done! Instead of a required uint when incrementing, I made it an Optional value, therefore you could also call the contract without providing a int and then it increments 1 by default.
